### ISSUE TITLE
Test send of image over lora

### ISSUE THREAD

**Issue by 0x6f736f646f** [nakujaproject/internship2022#44]
# Test send of image over Lora

## Requirements
Send one image over Lora and see what time it takes

## Deliverables
Arduino code to send images

## References
1. https://www.thethingsnetwork.org/forum/t/send-picture-via-lorawan/2407
2. https://iot.stackexchange.com/questions/4298/is-it-a-good-option-to-send-images-over-lora-network
3. Make sure you check [this](https://www.cs.usask.ca/faculty/makaroff/papers/tonghao-lorawan.pdf)
4. https://github.com/javl/slowimage

**Comment by bytecod3** [comment]
Done by this https://github.com/nakujaproject/N2Avionics-playground/commit/18c5939799fffc4f4bf97fc450e35c6c658ea126

**Comment by 0x6f736f646f** [comment]
This looks good

**Comment by 0x6f736f646f** [comment]
This looks good
