### ISSUE TITLE
Inquire about JKUAT satellite

### ISSUE THREAD

**Issue by 0x6f736f646f** [nakujaproject/internship2022#49]
# Inquire about JKUAT satellite

**Comment by 0x6f736f646f** [comment]
@junn-hope  provide the specs for this

**Comment by junn-hope** [comment]
@0x6f736f646f  We met the person in charge of this satellite on Monday,31st January. He confirmed that our idea of routing our traffic through this satellite can be done by creating a Wi-Fi network around our test area delivered by antennas set up point to point from transmitting antennas at Tech House. The Wi-Fi shall set up by a router connected to the receiver antenna. We can then configure our ESP32s, RaspberryPi and PCs to the same network.

A setup cost of approximately Ksh 30,000 was identified to coater for the cost of setup and for bandwidth.

**Comment by 0x6f736f646f** [comment]
Will not be implemented
