### ISSUE TITLE
Design architecture for ground station

### ISSUE THREAD

**Issue by 0x6f736f646f** [nakujaproject/internship2022#50]
# Design architecture for ground station

## Requirements
![image](https://user-images.githubusercontent.com/28790446/151654102-57729cef-2738-4a0a-be13-f6542cc73aa9.png)

@junn-hope upload the requirements for this issue

## Deliverables

- [ ] System architecture
- [ ] Sample demo

## References
1. http://mgsn.sourceforge.net/docs/arch1.1.php
2. http://openaccess.uoc.edu/webapps/o2/bitstream/10609/34981/7/jramosperezPFC0614memoria.pdf

**Comment by junn-hope** [comment]
@0x6f736f646f , @Mike-Kimani 
Open for review, this was our idea on how the architecture shall look like.

![image](https://user-images.githubusercontent.com/47918333/151972612-af3fcae0-6748-4eda-837b-926629a9567d.png)

**Comment by 0x6f736f646f** [comment]
It is not yet done until approval

**Comment by 0x6f736f646f** [comment]
Can you outline the steps in each process e.g

In Manager
- Receive data from esp32 receiver
- Decode the data
- Store the data
- Display the data

**Comment by 0x6f736f646f** [comment]
> @0x6f736f646f , @Mike-Kimani Open for review, this was our idea on how the architecture shall look like.
> 
> ![image](https://user-images.githubusercontent.com/47918333/151972612-af3fcae0-6748-4eda-837b-926629a9567d.png)

Good job @junn-hope and @bytecod3
